config/routes.rb
Rails.application.routes.draw do
  unauthenticated :user do
    root to: 'pages#home', as: :unauthenticated_root
  end

  authenticated :user do
    root to: 'players#playerpassing', as: :authenticated_root
  end

  get 'players/passing', to: 'players#playerpassing'
  get 'players/rushing', to: 'players#playerrushing'
  get 'players/receiving', to: 'players#playerreceiving'
  get 'teams/passing', to: 'teams#teampassing'
  get 'teams/rushing', to: 'teams#teamrushing'
  get 'teams/defense', to: 'teams#teamdefense'
  devise_for :users, controllers: {
    confirmations: 'confirmations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/playerpassing.rb
class Playerpassing < ApplicationRecord
end

app/models/playerreceiving.rb
class Playerreceiving < ApplicationRecord
end

app/models/playerrushing.rb
class Playerrushing < ApplicationRecord
end

app/models/teamdefense.rb
class Teamdefense < ApplicationRecord
end

app/models/teampassing.rb
class Teampassing < ApplicationRecord
end

app/models/teamrushing.rb
class Teamrushing < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :validatable, :confirmable, :lockable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController

  private def after_confirmation_path_for(resource_name, resource)
    sign_in(resource)
    players_passing_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :authenticate_user!

  def playerpassing
    @playerpassing = Playerpassing.all
  end

  def playerrushing
    @playerrushing = Playerrushing.all
  end

  def playerreceiving
    @playerreceiving = Playerreceiving.all
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :authenticate_user!

  def teampassing
    @teampassing = Teampassing.all
  end

  def teamrushing
    @teamrushing = Teamrushing.all
  end

  def teamdefense
    @teamdefense = Teamdefense.all
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
      <strong>
       #{pluralize(resource.errors.count, "error")} must be fixed
      </strong>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
        <%= value %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar sticky-top navbar-expand-md navbar-dark" id="app-navbar">
  <a class="navbar-brand">
    <%= link_to image_tag('Logo2Small-removebg-preview-resized'), authenticated_root_path, id: 'logo-signed-in' %>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" <%= link_to 'Player Stats', players_passing_path %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to 'Team Stats', teams_passing_path %></a>
      </li>
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_playernavbar.html.erb
<nav class="navbar navbar-expand-sm navbar-dark" id="player-navbar">
    <ul class="navbar-nav mr-auto" id="player-links">
      <li class="nav-item">
        <a class="nav-link" <%= link_to 'Passing', players_passing_path %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to 'Rushing', players_rushing_path %></a>
      </li>
      <li>
        <a class="nav-link" <%= link_to 'Receiving', players_receiving_path %></a>
      </li>
    </ul>
</nav>

app/views/layouts/_teamnavbar.html.erb
<nav class="navbar  navbar-expand-sm navbar-dark" id="team-navbar">
  <ul class="navbar-nav mr-auto" id="team-links">
      <li class="nav-item">
        <a class="nav-link" <%= link_to 'Passing', teams_passing_path %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to 'Rushing', teams_rushing_path %></a>
      </li>
      <li>
        <a class="nav-link" <%= link_to 'Defense', teams_defense_path %></a>
      </li>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <head>
    <title>Pro Football Stats</title>
    <%= csrf_meta_tags %>

    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js" charset="utf-8"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js" charset="utf-8"></script>

    <script src="https://cdn.datatables.net/fixedheader/3.1.7/js/dataTables.fixedHeader.min.js" charset="utf-8"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/fixedheader/3.1.7/css/fixedHeader.dataTables.min.css">


    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="turbolinks-cache-control" content="no-cache">

  </head>

  <body>
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
  </body>
</html>

app/views/layouts/home.html.erb
<% if current_user %>

<%= render 'layouts/navbar' %>

<h1>Welcome!</h1>

<% else %>

<body>
  <div class="form-background">
    <div class="container p-3">
      <div class="logo">
        <%= image_tag ('nfl-league-logo-small.png'), class: "logo-signed-out" %>
      </div>
        <%= button_to 'Sign In', new_user_session_path, method: :get, class: "btn" %>
        <%= button_to 'Sign Up', new_user_registration_path, method: :get, class: "btn" %>
    </div>
  </div>
</body>
<% end %>

app/views/pages/home.html.erb
<div class="form-background">
  <div class="container p-3">
    <div class="logo">
      <%= image_tag ('Logo2-removebg-preview.png'), class: "logo-signed-out" %>
    </div>
      <%= button_to 'Sign In', new_user_session_path, method: :get, class: "btn" %>
      <%= button_to 'Sign Up', new_user_registration_path, method: :get, class: "btn" %>
  </div>
</div>